### ISSUE TITLE
[regress] imagick is not installed on php8.0-fpm-alpine image

### ISSUE THREAD

**Issue by EvilBox** [docker-library/wordpress#619] opened 2021-06-28 20:23 UTC
Hi all, thanks for your docker image. Decided to upgrade php7.3 to php8 and found a problem:

**To Reproduce**
1. docker pull wordpress:php8.0-fpm-alpine and run (https://hub.docker.com/layers/wordpress/library/wordpress/php8.0-fpm-alpine/images/sha256-07138270737f6d621e3156268351b56ac910e3e6157c3005042283afc905ea64?context=explore)
2. navigate to - /wp-admin/site-health.php
3. WP health check reported - "The optional module, imagick, is not installed, or has been disabled."

**Expected behavior**
php module imagick included out of the box (as in php7.3) and passes WP health check

**Technical Information**
Docker 20.10.7
containerd v1.5.1
 
Thanks!

**Comment by wglambert** [comment] 2021-06-28 20:32
Duplicate of https://github.com/docker-library/wordpress/issues/616 ?

**Comment by tianon** [comment] 2021-06-29 00:03
This was intentional, actually, but could be resolved now that `imagick` has had an update:

https://github.com/docker-library/wordpress/blob/35f4b2751ed7ded4c9462a66346952df4a50e2d0/Dockerfile.template#L6-L11

**Closed** 2021-06-30 17:37 UTC
