### ISSUE TITLE
Request: just include WP-CLI or offer an image that has both

### ISSUE THREAD

**Issue by theDanielJLewis** [docker-library/wordpress#926] opened 2024-10-23 18:34 UTC
I've been trying for hours to get `wordpress:cli` to work in the Docker environment that Coolify uses. It all comes down to something that seems to be marking the CLI image as unhealthy, causing it to reboot over and over. But in the brief moment before it reboots, it _does_ have a connection to WordPress when the compose file is configured for shared environment variables, volumes, and dependencies. But it restarts nonetheless.

But it really shouldn't be this complicated. Why not simply include WP-CLI with the default WordPress image? Or offer a third image that includes both WordPress and the CLI? That would prevent this cumbersome setup just to get the CLI working. Plus, I think it makes more sense for the CLI and WordPress to actually be together.

**Comment by LaurentGoderre** [comment] 2024-10-23 22:03
If you are using compose with a cli image, the container would startup and the main process would have nothing to do and then would terminate and then create a restart loop.

If you want to have the CLI container stay up, you need to tell it to wait indefinitely using something like `tail -f /dev/null` as the command to keep it running

**Comment by theDanielJLewis** [comment] 2024-10-23 22:12
Funny, I figured out the "have nothing to do" part only about 30 minutes ago. But using `tail` is a brilliant way to keep it open!

Still, though, WP-CLI is such an indispensable tool for working with WordPress that I still think Docker should bundle it with the Docker official image.

(That is, of course, unless Matt goes nuclear against WP-CLI!)

Regardless, thanks for the tip, @LaurentGoderre! That gets me by for now, even though it's clunky.

You're the guy who "knew where to bang the hammer." 😎

**Comment by tianon** [comment] 2024-10-24 22:07
Duplicate of https://github.com/docker-library/wordpress/issues/283

(see especially https://github.com/docker-library/wordpress/issues/283#issuecomment-399591373)

**Closed by tianon** 2024-10-24 22:07 UTC

**Comment by theDanielJLewis** [comment] 2024-10-24 23:45
My bad. I was certain I searched before posting, couldn't find that other issue.
