### ISSUE TITLE
Fpm-alpine php 8.2 is broken

### ISSUE THREAD

**Issue by anver** [docker-library/wordpress#839] opened 2023-08-02 04:20 UTC
On a fresh install of provided fpm-alpine php 8.2, visiting the site says 

```
Your PHP installation appears to be missing the MySQL extension which is required by WordPress. php 8.2
```

**Comment by tianon** [comment] 2023-12-12 23:26
Sorry for the delay :grimacing:

Is this still applicable?  I can't seem to reproduce. :confused:

**Comment by tianon** [comment] 2023-12-12 23:26
(A minimal reproducer would be useful :see_no_evil:)

**Comment by anver** [comment] 2023-12-14 15:45
It still exists but this time i used alpine php 8.3 image instead of 8.2

![image](https://github.com/docker-library/wordpress/assets/506491/372e446c-9550-4f5e-a612-c438a4d0eb35)

**Comment by tianon** [comment] 2023-12-14 18:47
Where should I browse in the UI to see that?  I've just deployed `wordpress:php8.3-fpm-alpine` locally with NGINX in front (NGINX config from https://gist.github.com/md5/d9206eacb5a0ff5d6be0), and it seems to be working fine. :see_no_evil:

![image](https://github.com/docker-library/wordpress/assets/161631/2f361735-5b45-42e6-bf14-c408fed0acaf)

**Comment by tianon** [comment] 2023-12-14 18:47
```console
$ docker exec -i wordpress_wordpress_1 php -i | grep mysqli
/usr/local/etc/php/conf.d/docker-php-ext-mysqli.ini,
mysqli
mysqli.allow_local_infile => Off => Off
mysqli.allow_persistent => On => On
mysqli.default_host => no value => no value
mysqli.default_port => 3306 => 3306
mysqli.default_pw => no value => no value
mysqli.default_socket => no value => no value
mysqli.default_user => no value => no value
mysqli.local_infile_directory => no value => no value
mysqli.max_links => Unlimited => Unlimited
mysqli.max_persistent => Unlimited => Unlimited
mysqli.rollback_on_cached_plink => Off => Off
API Extensions => mysqli
```

**Comment by hktr92** [comment] 2023-12-26 13:55
It seems that the image itself doesn't contain PDO_MYSQL extension at all: https://github.com/docker-library/wordpress/blob/master/Dockerfile.template#L76-L82, thus breaking WooCommerce using this image.

However, as a temporary workaround, you can override the base image:
```dockerfile
FROM wordpress:6-php8.3-fpm-alpine AS wp-base

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN install-php-extensions pdo pdo_mysql
```

For simplicity, just put it where you have the `docker-compose.yml` file and, for clarity, name it `Dockerfile.wordpress`.

And inside your `docker-compose.yml`, replace the following code where you have `image: wordpress`:
```yaml
    build:
      dockerfile: Dockerfile.wordpress
    ...
```

**Comment by tianon** [comment] 2024-01-02 19:52
> It seems that the image itself doesn't contain PDO_MYSQL extension at all: ...

Correct; that is intentional: https://hub.docker.com/_/wordpress#:~:text=This%20image%20does%20not%20provide%20any%20additional%20PHP%20extensions%20or%20other%20libraries%2C%20even%20if%20they%20are%20required%20by%20popular%20plugins%20(e.g.%20it%20cannot%20send%20e%2Dmails).

> This image does not provide any additional PHP extensions or other libraries, even if they are required by popular plugins (e.g. [it cannot send e-mails](https://github.com/docker-library/wordpress/issues/30)). There are an infinite number of possible plugins, and they potentially require any extension PHP supports. Including every PHP extension that exists would dramatically increase the image size.
> 
> If you need additional PHP extensions, you'll need to create your own image `FROM` this one. The [documentation of the `php` image](https://github.com/docker-library/docs/blob/master/php/README.md#how-to-install-more-php-extensions) explains how to compile additional extensions. Additionally, [an older `Dockerfile` for `wordpress`](https://github.com/docker-library/wordpress/blob/618490d4bdff6c5774b84b717979bfe3d6ba8ad1/apache/Dockerfile#L5-L9) has a simplified example of doing this and [a newer version of that same `Dockerfile`](https://github.com/docker-library/wordpress/blob/5bbbfa8909232af10ea3fea8b80302a6041a2d04/latest/php7.4/apache/Dockerfile#L18-L62) has a much more thorough example.

**Comment by yosifkit** [comment] 2024-07-02 22:27
Closing, since any extra PHP extensions needed by WordPress plugins must be installed by the user.

**Closed by yosifkit** 2024-07-02 22:27 UTC
