### ISSUE TITLE
Function mail() not working 

### ISSUE THREAD

**Issue by Julianoe** [docker-library/wordpress#262] opened 2017-12-18 17:01 UTC
Shouldn't the default docker image for Wordpress include at least something to make the password recovery work? (discussion related to this issue https://github.com/docker-library/wordpress/issues/30 )

**Comment by tianon** [comment] 2017-12-18 17:04
This is not only related to #30, but is a duplicate of #30. :wink:

**Closed by tianon** 2017-12-18 17:04 UTC

**Comment by Julianoe** [comment] 2017-12-19 03:08
I meant to bring the conversation towards adding something either in the image itself (debatable) or at least documentation-wise. I mean i understand the fact that we avoid clogging the image with things that could be specific to plugins or use-case. But recovery password mailing should work out-of-the-box for end user that have to use wordpress

**Comment by tianon** [comment] 2017-12-27 23:26
I agree that it'd be great to have working out of the box, but given the complication involved in sending email, it's too environment specific for us to reasonably do so.  Sorry!
