### ISSUE TITLE
docker-entrypoint.sh inconsistent overwrite behavior. Fix tried details inside

### ISSUE THREAD

**Issue by ritesht** [docker-library/wordpress#529] opened 2020-09-11 01:43 UTC
Current code has no-overwrite-dir option for tar during extraction this behaves inconsistently for some reason when the container is run on mac vs on GCP/Cloud Run option. This beats me since I would expect containers to behave exactly the same no matter which host OS they are run on. I have some theories and may be someone else can help explain the mystery. In any case, here is the explanation of the difference between 2 similar options for tar to avoid overwrite of the existing files. Details are here https://www.gnu.org/software/tar/manual/html_node/Dealing-with-Old-Files.html. Essentially no-overwrite seems to just handle the metadata while the skip-old-file option actually skips the overwriting these files.

I have verified this is working as expected after changing from no-overwrite to skip-old-files.

targetTarArgs+=(--no-overwrite-dir) Needs to be changed to targetTarArgs+=( --skip-old-files)
tar "${sourceTarArgs[@]}" . | tar "${targetTarArgs[@]}"

**Comment by tianon** [comment] 2020-12-19 01:15
This was added in 155958d04182c67cae44579de55ea4cc99bd9036 specifically because we were having trouble with metadata on `/var/www/html` trying to be set (as noted in that commit message) - I don't think it was intended to stop *other* files from being overwritten. :confused:

Do you have an example we can use to reproduce the issue?  (My guess is something related to the way host->container file sharing works on Docker for Mac, but it would help to know which environment is the "working" one.)

**Comment by jonathanlaf** [comment] 2021-01-26 23:55
I don' t know if it's related or not, but, i'm using latest to build my wordpress container, but i'm trying to inject a mu-plugins into the image and it get deleted when wordpress file are copied.

```
FROM wordpress:latest

...

WORKDIR /var/www/html
RUN mkdir -p /var/www/html/wp-content/mu-plugins/
COPY ./mu-plugins/mailhog.php ./wp-content/mu-plugins/mailhog.php
```

**Comment by tianon** [comment] 2021-01-27 00:06
@jonathanlaf that's more likely to be because `/var/www/html` is a `VOLUME` (#232) -- I'd suggest you copy your contents to `/usr/src/wordpress` instead which will *probably* work

**Comment by tianon** [comment] 2021-03-23 22:40
Closing given the lack of a reproducer -- if there's a simple example for reproducing, this is something we'd love to look into deeper!

**Closed by tianon** 2021-03-23 22:40 UTC

**Comment by hdpe** [comment] 2021-09-13 08:56
I can reproduce this issue, although I really don't understand it. I just could not understand why the image built on Circle CI vs one built locally on Mac OS had different files in the running container.

Set up (bash):

```
mkdir wordpress-docker-repro && cd $_
echo 'FROM wordpress
RUN touch /var/www/html/wp-content/plugins/fake-plugin' > Dockerfile
docker build -t wordpress-docker-repro .
docker run --name wordpress-docker-repro --rm -d wordpress-docker-repro
```

then:

```
docker exec wordpress-docker-repro bash -c 'ls /var/www/html/wp-content/plugins'
```

On Mac OS (Docker version 20.10.7, build f0df350) this gives:

```
akismet
fake-plugin
hello.php
index.php
```

Running exactly the same steps on a local Linux VM (Fedora 32, Docker version 19.03.11, build 42e35e6) gives:

```
akismet
hello.php
index.php
```

**Comment by yosifkit** [comment] 2021-09-13 17:24
Correct, `/var/www/html/` is defined as a `VOLUME`, so no files should ever persist there during a build. Whatever is doing the building on Docker for Mac (likely buildkit), is wrong and has a bug.
