### ISSUE TITLE
php8.1-fpm-alpine error on fresh installation (NOTICE: PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'wordpress.wp_options' doesn't exist in /var/www/html/wp-includes/wp-db.php:2056)

### ISSUE THREAD

**Issue by maltris** [docker-library/wordpress#680] opened 2022-01-14 18:05 UTC
Hello, running wordpress:php8.1-fpm-alpine on an empty db and filesystem logs

```
Jan 14 18:39:31 localhost docker/root_fpm_1[41453]: WordPress not found in /var/www/html - copying now...
Jan 14 18:39:32 localhost docker/root_fpm_1[41453]: Complete! WordPress has been successfully copied to /var/www/html
Jan 14 18:39:32 localhost docker/root_fpm_1[41453]: No 'wp-config.php' found in /var/www/html, but 'WORDPRESS_...' variables supplied; copying 'wp-config-docker.php' (WORDPRESS_DB_HOST WORDPRESS_DB_NAME WORDPRESS_DB_PASSWORD WORDPRESS_DB_USER)
Jan 14 18:39:32 localhost docker/root_fpm_1[41453]: [14-Jan-2022 17:39:32] NOTICE: fpm is running, pid 1
Jan 14 18:39:32 localhost docker/root_fpm_1[41453]: [14-Jan-2022 17:39:32] NOTICE: ready to handle connections
Jan 14 18:39:57 localhost docker/root_fpm_1[41453]: NOTICE: PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'wordpress.wp_options' doesn't exist in /var/www/html/wp-includes/wp-db.php:2056
Jan 14 18:39:57 localhost docker/root_fpm_1[41453]: Stack trace:
Jan 14 18:39:57 localhost docker/root_fpm_1[41453]: #0 /var/www/html/wp-includes/wp-db.php(2056): mysqli_query(Object(mysqli), 'SELECT option_n...')
Jan 14 18:39:57 localhost docker/root_fpm_1[41453]: #1 /var/www/html/wp-includes/wp-db.php(1945): wpdb->_do_query('SELECT option_n...')
Jan 14 18:39:57 localhost docker/root_fpm_1[41453]: #2 /var/www/html/wp-includes/wp-db.php(2695): wpdb->query('SELECT option_n...')
Jan 14 18:39:57 localhost docker/root_fpm_1[41453]: #3 /var/www/html/wp-includes/option.php(284): wpdb->get_results('SELECT option_n...')
Jan 14 18:39:57 localhost docker/root_fpm_1[41453]: #4 /var/www/html/wp-includes/functions.php(1730): wp_load_alloptions()
Jan 14 18:39:57 localhost docker/root_fpm_1[41453]: #5 /var/www/html/wp-includes/load.php(752): is_blog_installed()
Jan 14 18:39:57 localhost docker/root_fpm_1[41453]: #6 /var/www/html/wp-settings.php(159): wp_not_installed()
Jan 14 18:39:57 localhost docker/root_fpm_1[41453]: #7 /var/www/html/wp-config.php(133): require_once('/var/www/html/w...')
Jan 14 18:39:57 localhost docker/root_fpm_1[41453]: #8 /var/www/html/wp-load.php(50): require_once('/var/www/html/w...')
Jan 14 18:39:57 localhost docker/root_fpm_1[41453]: #9 /var/www/html/wp-blog-header.php(13): require_once('/var/www/html/w...')
Jan 14 18:39:57 localhost docker/root_fpm_1[41453]: #10 /var/www/html/index.php(17): require('/var/www/html/w...')
Jan 14 18:39:57 localhost docker/root_fpm_1[41453]: #11 {main}
Jan 14 18:39:57 localhost docker/root_fpm_1[41453]:   thrown in /var/www/html/wp-includes/wp-db.php on line 2056
```

and returns a 500 error. Switching to wordpress:php8.0-fpm-alpine works fine.

**Comment by tianon** [comment] 2022-01-14 18:09
Duplicate of https://github.com/docker-library/wordpress/discussions/677

**Closed by tianon** 2022-01-14 18:09 UTC
