### ISSUE TITLE
Include php7-zip for various extensions

### ISSUE THREAD

**Issue by PixiBixi** [docker-library/wordpress#284] opened 2018-02-26 22:21 UTC
Hi everyone

Since the PHP 7.0, the zip class is removed from the main-package. 

However, its useful for lots of extensions like Duplicator (https://wordpress.org/plugins/duplicator/)

I've been able to install-it, but its more a workaround than a viable solution : (zlib1g-dev is a mandatory for compile php7.X-zip

```bash
curl -o  package.deb http://ftp.bg.debian.org/debian/pool/main/z/zlib/zlib1g-dev_1.2.8.dfsg-2+b1_amd64.deb 
dpkg -i package.deb
docker-php-ext-configure zip
docker-php-ext-install zip
docker-php-ext-enable zip
```

**Comment by tianon** [comment] 2018-02-26 22:38
Duplicate of #213; see especially https://github.com/docker-library/wordpress/issues/213#issuecomment-337260184.

**Closed by tianon** 2018-02-26 22:38 UTC
