### ISSUE TITLE
wp-content/uploads is not writable in 4.9.8 image

### ISSUE THREAD

**Issue by tofumatt** [docker-library/wordpress#322] opened 2018-08-03 09:11 UTC
We're encountering issues over at https://github.com/wordpress/gutenberg with the latest `wordpress` image (4.9.8). See: https://github.com/WordPress/gutenberg/issues/8418

We can't run `wp-cli core update` because `wp-content/uploads` is not writable. This line errors: https://github.com/WordPress/gutenberg/blob/master/bin/install-wordpress.sh#L52 with the bug in the above issue.

I don't know what caused this change because I'm finding it hard to track how/where this image is built from, but changing back to 4.9.7 image (changing the image we use from `wordpress` to `wordpress:4.9.7` in our `docker-compose.yml`) "fixes" the issue.

Removing that update command things seem to also run okay, but we should be able to run it. I think eventually anything else that interacts with that folder will cause errors.

Was a permission changed or something?

**Comment by tofumatt** [comment] 2018-08-03 11:22
It's possible this isn't your fault actually, I just have no idea what's up. It seems that WP CLI can't update without an error. Running `wp-cli core update` against the `wordpress` image runs into errors.

**Comment by tofumatt** [comment] 2018-08-03 13:01
Turns out this is a permissions issue. Adding `-u 33` to our `wp-cli` commands (using the `wordpress:cli` image) makes it work, but I wonder why that's needed at all.

I'll leave it to you if you want to leave this open, as I think requiring the `-u 33` argument is quite weird, but it seems this isn't exactly the issue I thought it was...

**Comment by wglambert** [comment] 2018-08-03 17:49
Discussion on issue here https://github.com/WordPress/gutenberg/pull/8427

**Comment by tianon** [comment] 2018-08-03 19:12
I think this is actually a duplicate of https://github.com/docker-library/wordpress/issues/256. :+1:

**Comment by tofumatt** [comment] 2018-08-07 23:51
> I think this is actually a duplicate of #256. 👍

Sounds right. I get why resolving this one is tough and the solutions in #256 seem okay to me... Maybe to resolve this the docs could at least mention the solutions in #256? 🤷‍♂️

**Comment by tianon** [comment] 2018-08-13 22:58
Good idea; added a little blurb over in https://github.com/docker-library/docs/pull/1284. :+1:

**Closed by tianon** 2018-08-13 22:58 UTC
Labels: question
