### ISSUE TITLE
VOLUME makes it not possible to create files inside /var/www/html

### ISSUE THREAD

**Issue by michaelschem** [docker-library/wordpress#662] opened 2021-11-18 23:28 UTC
I'm using the image [php7.3-apache](https://github.com/docker-library/wordpress/blob/4d82a6aefbe895b0a9f3d809bd2959c2dd1710fd/latest/php7.3/apache/Dockerfile) in my Dockerfile.

During one of the steps I do a `composer install` which creates a vendor folder, but since this is a VOLUME, it is only available in that step and not when the app is started and needs those files. Can this be removed?

**Comment by wglambert** [comment] 2021-11-18 23:46
See https://github.com/docker-library/wordpress/issues/232#issuecomment-340613133 and this comment https://github.com/docker-library/wordpress/issues/232#issuecomment-420767663

**Comment by tianon** [comment] 2022-06-11 00:35
Closing as a duplicate of #232

**Closed by tianon** 2022-06-11 00:35 UTC
Labels: question
