### ISSUE TITLE
Add  mcrypt extension

### ISSUE THREAD

**Issue by kristianstroka** [docker-library/wordpress#435] opened 2019-09-23 11:59 UTC
A lot of plugins still requires mcrypt extension. Is possible to add this extention to dockerized wp?

**Comment by wglambert** [comment] 2019-09-23 16:35
https://github.com/docker-library/docs/tree/master/wordpress#adding-additional-libraries--extensions

```Dockerfile
FROM wordpress

RUN set -ex; \
        apt update; apt install -y libmcrypt-dev; \
        pecl install mcrypt; \
        docker-php-ext-enable mcrypt; \
        rm -rf /var/lib/apt/lists/*
```

```console
$ docker build . -t wordpress:test
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM wordpress
 ---> 3ee8f0d4f2c0
Step 2/2 : RUN set -ex;         apt update; apt install -y libmcrypt-dev;       pecl install mcrypt;    docker-php-ext-enable mcrypt; rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> bd7fe23ca4e6
Successfully built bd7fe23ca4e6
Successfully tagged wordpress:test

$ docker run --rm wordpress:test php -i | grep -i mcrypt
/usr/local/etc/php/conf.d/docker-php-ext-mcrypt.ini,
Registered Stream Filters => zlib.*, convert.iconv.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk, mcrypt.*, mdecrypt.*
mcrypt
mcrypt support => enabled
mcrypt_filter support => enabled
mcrypt.algorithms_dir => no value => no value
mcrypt.modes_dir => no value => no value
```

**Comment by wglambert** [comment] 2019-09-23 22:58
Closing since adding extensions is in the docs and this seems to be a duplicate of https://github.com/docker-library/wordpress/issues/68

**Closed by wglambert** 2019-09-23 22:58 UTC
Labels: question
