### ISSUE TITLE
Updating wp-config.php doesn't update the website

### ISSUE THREAD

**Issue by saurabhkgig** [docker-library/wordpress#459] opened 2020-01-03 09:24 UTC
**Our Requirement**
We want to dockerize the existing wordpress appllication with external MySQL DB & for that 
Instead of configuring DB details through UI, I directly added wp-config.php file under  **/var/www/html** and refreshed the page.
Instead of returning _wp-admin_ panel it open a window saying wp-config.php already exists.
I've attached the screenshot, clicking the blue link returns the panel as expected.

In case of continous deployment this will not be acceptable for users of website. Is there a better way to integrate this config file & make it seamless for the continuous deployment . Please suggest.

<img width="1425" alt="Screenshot 2020-01-03 at 2 48 11 PM" src="https://user-images.githubusercontent.com/59470659/71715686-4b9f5180-2e38-11ea-8496-5e97bf4ea940.png">

**Comment by wglambert** [comment] 2020-01-03 18:06
I wasn't able to reproduce your issue with supplying a `wp-config.php`

The `docker-compose.yml`; note the environment variables commented out, I grabbed the working `wp-config.php` from a previous initialization to then mount into the new container
```yaml
version: '3.1'
  
services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
        #    environment:
        #      WORDPRESS_DB_HOST: db
        #      WORDPRESS_DB_USER: exampleuser
        #      WORDPRESS_DB_PASSWORD: examplepass
        #      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
      - ./wp-config.php:/var/www/html/wp-config.php

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
```

```console
$ docker-compose up -d  
Creating network "wordpress_default" with the default driver
Creating volume "wordpress_wordpress" with default driver
Creating volume "wordpress_db" with default driver
Creating wordpress_db_1        ... done
Creating wordpress_wordpress_1 ... done
```
<details>
<summary> docker logs of initialization</summary>

```console
$ docker-compose logs -f
Attaching to wordpress_wordpress_1, wordpress_db_1
wordpress_1  | WordPress not found in /var/www/html - copying now...
wordpress_1  | WARNING: /var/www/html is not empty! (copying anyhow)
wordpress_1  | Complete! WordPress has been successfully copied to /var/www/html
wordpress_1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.192.2. Set the 'ServerName' directive globally to suppress this message
wordpress_1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.192.2. Set the 'ServerName' directive globally to suppress this message
wordpress_1  | [Fri Jan 03 17:51:14.491561 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.3.13 configured -- resuming normal operations
wordpress_1  | [Fri Jan 03 17:51:14.491597 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
db_1         | 2020-01-03 17:51:15+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.28-1debian9 started.
db_1         | 2020-01-03 17:51:15+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
db_1         | 2020-01-03 17:51:15+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.28-1debian9 started.
db_1         | 2020-01-03 17:51:15+00:00 [Note] [Entrypoint]: Initializing database files
db_1         | 2020-01-03T17:51:15.987184Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
db_1         | 2020-01-03T17:51:26.096292Z 0 [Warning] InnoDB: New log files created, LSN=45790
db_1         | 2020-01-03T17:51:29.289862Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
db_1         | 2020-01-03T17:51:30.487312Z 0 [Warning] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: ac3916c8-2e51-11ea-bd8f-0242c0a8c003.
db_1         | 2020-01-03T17:51:31.192643Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
db_1         | 2020-01-03T17:51:31.909721Z 0 [Warning] CA certificate ca.pem is self signed.
db_1         | 2020-01-03T17:51:32.034966Z 1 [Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
db_1         | 2020-01-03 17:54:44+00:00 [Note] [Entrypoint]: Database files initialized
db_1         | 2020-01-03 17:54:44+00:00 [Note] [Entrypoint]: Starting temporary server
db_1         | 2020-01-03 17:54:44+00:00 [Note] [Entrypoint]: Waiting for server startup
db_1         | 2020-01-03T17:54:44.460700Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
db_1         | 2020-01-03T17:54:44.462319Z 0 [Note] mysqld (mysqld 5.7.28) starting as process 81 ...
db_1         | 2020-01-03T17:54:44.466575Z 0 [Note] InnoDB: PUNCH HOLE support available
db_1         | 2020-01-03T17:54:44.466596Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1         | 2020-01-03T17:54:44.466601Z 0 [Note] InnoDB: Uses event mutexes
db_1         | 2020-01-03T17:54:44.466605Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
db_1         | 2020-01-03T17:54:44.466609Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
db_1         | 2020-01-03T17:54:44.466613Z 0 [Note] InnoDB: Using Linux native AIO
db_1         | 2020-01-03T17:54:44.466893Z 0 [Note] InnoDB: Number of pools: 1
db_1         | 2020-01-03T17:54:44.466996Z 0 [Note] InnoDB: Using CPU crc32 instructions
db_1         | 2020-01-03T17:54:44.468627Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
db_1         | 2020-01-03T17:54:44.478144Z 0 [Note] InnoDB: Completed initialization of buffer pool
db_1         | 2020-01-03T17:54:44.479881Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1         | 2020-01-03T17:54:44.493680Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
db_1         | 2020-01-03T17:54:44.579025Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1         | 2020-01-03T17:54:44.579179Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1         | 2020-01-03T17:54:45.808191Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1         | 2020-01-03T17:54:45.811200Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
db_1         | 2020-01-03T17:54:45.811242Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
db_1         | 2020-01-03T17:54:45.812357Z 0 [Note] InnoDB: Waiting for purge to start
db_1         | 2020-01-03T17:54:45.862718Z 0 [Note] InnoDB: 5.7.28 started; log sequence number 2630255
db_1         | 2020-01-03T17:54:45.863318Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1         | 2020-01-03T17:54:45.863988Z 0 [Note] Plugin 'FEDERATED' is disabled.
db_1         | 2020-01-03T17:54:45.868884Z 0 [Note] InnoDB: Buffer pool(s) load completed at 200103 17:54:45
db_1         | 2020-01-03T17:54:45.883264Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
db_1         | 2020-01-03T17:54:45.883307Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
db_1         | 2020-01-03T17:54:45.885711Z 0 [Warning] CA certificate ca.pem is self signed.
db_1         | 2020-01-03T17:54:45.885820Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
db_1         | 2020-01-03T17:54:46.033348Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
db_1         | 2020-01-03T17:54:46.060810Z 0 [Note] Event Scheduler: Loaded 0 events
db_1         | 2020-01-03T17:54:46.061184Z 0 [Note] mysqld: ready for connections.
db_1         | Version: '5.7.28'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server (GPL)
db_1         | 2020-01-03 17:54:46+00:00 [Note] [Entrypoint]: Temporary server started.
db_1         | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
db_1         | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
db_1         | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
db_1         | Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
db_1         | 2020-01-03 17:54:59+00:00 [Note] [Entrypoint]: GENERATED ROOT PASSWORD: ievah6XieM4OoPh5bo7aifob3ochait9
db_1         | 2020-01-03 17:54:59+00:00 [Note] [Entrypoint]: Creating database exampledb
db_1         | 2020-01-03 17:54:59+00:00 [Note] [Entrypoint]: Creating user exampleuser
db_1         | 2020-01-03 17:54:59+00:00 [Note] [Entrypoint]: Giving user exampleuser access to schema exampledb
db_1         | 
db_1         | 2020-01-03 17:54:59+00:00 [Note] [Entrypoint]: Stopping temporary server
db_1         | 2020-01-03T17:54:59.211572Z 0 [Note] Giving 0 client threads a chance to die gracefully
db_1         | 2020-01-03T17:54:59.211594Z 0 [Note] Shutting down slave threads
db_1         | 2020-01-03T17:54:59.211598Z 0 [Note] Forcefully disconnecting 0 remaining clients
db_1         | 2020-01-03T17:54:59.211603Z 0 [Note] Event Scheduler: Purging the queue. 0 events
db_1         | 2020-01-03T17:54:59.211637Z 0 [Note] Binlog end
db_1         | 2020-01-03T17:54:59.212181Z 0 [Note] Shutting down plugin 'ngram'
db_1         | 2020-01-03T17:54:59.212193Z 0 [Note] Shutting down plugin 'partition'
db_1         | 2020-01-03T17:54:59.212198Z 0 [Note] Shutting down plugin 'BLACKHOLE'
db_1         | 2020-01-03T17:54:59.212203Z 0 [Note] Shutting down plugin 'ARCHIVE'
db_1         | 2020-01-03T17:54:59.212207Z 0 [Note] Shutting down plugin 'PERFORMANCE_SCHEMA'
db_1         | 2020-01-03T17:54:59.212237Z 0 [Note] Shutting down plugin 'MRG_MYISAM'
db_1         | 2020-01-03T17:54:59.212245Z 0 [Note] Shutting down plugin 'MyISAM'
db_1         | 2020-01-03T17:54:59.212253Z 0 [Note] Shutting down plugin 'INNODB_SYS_VIRTUAL'
db_1         | 2020-01-03T17:54:59.212259Z 0 [Note] Shutting down plugin 'INNODB_SYS_DATAFILES'
db_1         | 2020-01-03T17:54:59.212264Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESPACES'
db_1         | 2020-01-03T17:54:59.212267Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN_COLS'
db_1         | 2020-01-03T17:54:59.212271Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN'
db_1         | 2020-01-03T17:54:59.212274Z 0 [Note] Shutting down plugin 'INNODB_SYS_FIELDS'
db_1         | 2020-01-03T17:54:59.212278Z 0 [Note] Shutting down plugin 'INNODB_SYS_COLUMNS'
db_1         | 2020-01-03T17:54:59.212281Z 0 [Note] Shutting down plugin 'INNODB_SYS_INDEXES'
db_1         | 2020-01-03T17:54:59.212285Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESTATS'
db_1         | 2020-01-03T17:54:59.212289Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLES'
db_1         | 2020-01-03T17:54:59.212292Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_TABLE'
db_1         | 2020-01-03T17:54:59.212296Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_CACHE'
db_1         | 2020-01-03T17:54:59.212300Z 0 [Note] Shutting down plugin 'INNODB_FT_CONFIG'
db_1         | 2020-01-03T17:54:59.212304Z 0 [Note] Shutting down plugin 'INNODB_FT_BEING_DELETED'
db_1         | 2020-01-03T17:54:59.212307Z 0 [Note] Shutting down plugin 'INNODB_FT_DELETED'
db_1         | 2020-01-03T17:54:59.212311Z 0 [Note] Shutting down plugin 'INNODB_FT_DEFAULT_STOPWORD'
db_1         | 2020-01-03T17:54:59.212315Z 0 [Note] Shutting down plugin 'INNODB_METRICS'
db_1         | 2020-01-03T17:54:59.212319Z 0 [Note] Shutting down plugin 'INNODB_TEMP_TABLE_INFO'
db_1         | 2020-01-03T17:54:59.212322Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_POOL_STATS'
db_1         | 2020-01-03T17:54:59.212326Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE_LRU'
db_1         | 2020-01-03T17:54:59.212330Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE'
db_1         | 2020-01-03T17:54:59.212334Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX_RESET'
db_1         | 2020-01-03T17:54:59.212337Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX'
db_1         | 2020-01-03T17:54:59.212341Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM_RESET'
db_1         | 2020-01-03T17:54:59.212344Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM'
db_1         | 2020-01-03T17:54:59.212348Z 0 [Note] Shutting down plugin 'INNODB_CMP_RESET'
db_1         | 2020-01-03T17:54:59.212352Z 0 [Note] Shutting down plugin 'INNODB_CMP'
db_1         | 2020-01-03T17:54:59.212355Z 0 [Note] Shutting down plugin 'INNODB_LOCK_WAITS'
db_1         | 2020-01-03T17:54:59.212359Z 0 [Note] Shutting down plugin 'INNODB_LOCKS'
db_1         | 2020-01-03T17:54:59.212362Z 0 [Note] Shutting down plugin 'INNODB_TRX'
db_1         | 2020-01-03T17:54:59.212366Z 0 [Note] Shutting down plugin 'InnoDB'
db_1         | 2020-01-03T17:54:59.212425Z 0 [Note] InnoDB: FTS optimize thread exiting.
db_1         | 2020-01-03T17:54:59.212538Z 0 [Note] InnoDB: Starting shutdown...
db_1         | 2020-01-03T17:54:59.312936Z 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
db_1         | 2020-01-03T17:54:59.386090Z 0 [Note] InnoDB: Buffer pool(s) dump completed at 200103 17:54:59
db_1         | 2020-01-03T17:55:03.198189Z 0 [Note] InnoDB: Shutdown completed; log sequence number 12442428
db_1         | 2020-01-03T17:55:03.203453Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
db_1         | 2020-01-03T17:55:03.203510Z 0 [Note] Shutting down plugin 'MEMORY'
db_1         | 2020-01-03T17:55:03.203523Z 0 [Note] Shutting down plugin 'CSV'
db_1         | 2020-01-03T17:55:03.203534Z 0 [Note] Shutting down plugin 'sha256_password'
db_1         | 2020-01-03T17:55:03.203542Z 0 [Note] Shutting down plugin 'mysql_native_password'
db_1         | 2020-01-03T17:55:03.203893Z 0 [Note] Shutting down plugin 'binlog'
db_1         | 2020-01-03T17:55:03.206861Z 0 [Note] mysqld: Shutdown complete
db_1         | 
db_1         | 2020-01-03 17:55:03+00:00 [Note] [Entrypoint]: Temporary server stopped
db_1         | 
db_1         | 2020-01-03 17:55:03+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.
db_1         | 
db_1         | 2020-01-03T17:55:03.426129Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
db_1         | 2020-01-03T17:55:03.427689Z 0 [Note] mysqld (mysqld 5.7.28) starting as process 1 ...
db_1         | 2020-01-03T17:55:03.431363Z 0 [Note] InnoDB: PUNCH HOLE support available
db_1         | 2020-01-03T17:55:03.431381Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1         | 2020-01-03T17:55:03.431385Z 0 [Note] InnoDB: Uses event mutexes
db_1         | 2020-01-03T17:55:03.431388Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
db_1         | 2020-01-03T17:55:03.431391Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
db_1         | 2020-01-03T17:55:03.431394Z 0 [Note] InnoDB: Using Linux native AIO
db_1         | 2020-01-03T17:55:03.431650Z 0 [Note] InnoDB: Number of pools: 1
db_1         | 2020-01-03T17:55:03.431768Z 0 [Note] InnoDB: Using CPU crc32 instructions
db_1         | 2020-01-03T17:55:03.433199Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
db_1         | 2020-01-03T17:55:03.443091Z 0 [Note] InnoDB: Completed initialization of buffer pool
db_1         | 2020-01-03T17:55:03.444892Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1         | 2020-01-03T17:55:03.457485Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
db_1         | 2020-01-03T17:55:05.054754Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1         | 2020-01-03T17:55:05.054818Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1         | 2020-01-03T17:55:05.676609Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1         | 2020-01-03T17:55:05.679086Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
db_1         | 2020-01-03T17:55:05.679122Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
db_1         | 2020-01-03T17:55:05.680456Z 0 [Note] InnoDB: 5.7.28 started; log sequence number 12442428
db_1         | 2020-01-03T17:55:05.681251Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1         | 2020-01-03T17:55:05.681766Z 0 [Note] Plugin 'FEDERATED' is disabled.
db_1         | 2020-01-03T17:55:05.690571Z 0 [Note] InnoDB: Buffer pool(s) load completed at 200103 17:55:05
db_1         | 2020-01-03T17:55:05.700169Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
db_1         | 2020-01-03T17:55:05.700204Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
db_1         | 2020-01-03T17:55:05.702821Z 0 [Warning] CA certificate ca.pem is self signed.
db_1         | 2020-01-03T17:55:05.702908Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
db_1         | 2020-01-03T17:55:05.704291Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
db_1         | 2020-01-03T17:55:05.704377Z 0 [Note] IPv6 is available.
db_1         | 2020-01-03T17:55:05.704406Z 0 [Note]   - '::' resolves to '::';
db_1         | 2020-01-03T17:55:05.704444Z 0 [Note] Server socket created on IP: '::'.
db_1         | 2020-01-03T17:55:06.211241Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
db_1         | 2020-01-03T17:55:06.240100Z 0 [Note] Event Scheduler: Loaded 0 events
db_1         | 2020-01-03T17:55:06.240654Z 0 [Note] mysqld: ready for connections.
db_1         | Version: '5.7.28'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
```
</details>

After a few minutes mysql is initialized and I fill out user details for the wordpress setup
![image](https://user-images.githubusercontent.com/26428991/71740267-9c9b4f80-2e10-11ea-99d2-d292eace6b64.png)


Then it's done, the `wp-config.php` has the correct database information

![image](https://user-images.githubusercontent.com/26428991/71740137-50500f80-2e10-11ea-89cc-a3e6787012cd.png)

**Comment by saurabhkgig** [comment] 2020-01-03 18:25
You can reproduce this issue now. Above steps taken by you are first time setup for wordpress docker.
To replicate:
Remove wp-config.php from /var/www/html 
Refresh your webpage, it will ask for DB configs. Don't update there in UI
Now add your wp-config.php and refresh the webpage again.

**Comment by wglambert** [comment] 2020-01-03 18:45
```console
root@85e42060794d:/var/www/html# rm -f wp-config.php                                                                                              
rm: cannot remove 'wp-config.php': Device or resource busy
```

I don't believe this file is meant to be modified while WordPress is using it, so restarting the container seems necessary for such changes, and to minimize downtime on that you could load balance connections to a new WordPress container with the modified file. IE a [canary deployment](https://en.wikipedia.org/wiki/Deployment_environment#Production)

But this seems like intended behavior and not something specific to the containerized version. I would imagine you have to stop WordPress to modify that file anyway.

If there's documentation showing that this file is able to be hot-swapped while WordPress is running then we can definitely look to see how we could implement that functionality as it exists outside of a container environment.

**Comment by wglambert** [comment] 2020-01-22 13:26
From https://wordpress.org/support/article/editing-wp-config-php/#double-check-before-saving
>Upload the file to your web server and you’re ready to install WordPress!

All I gather is that the file is meant to be modified before an install (or I suppose in-between restarts) when wordpress isn't currently using the file, so I'm going to close the issue.

**Closed by wglambert** 2020-01-22 13:26 UTC
Labels: question
