### ISSUE TITLE
Using local volume changes /var/www/html rights

### ISSUE THREAD

**Issue by nigel-daniels** [docker-library/wordpress#97] opened 2015-08-25 17:10 UTC
I noticed that when I map the /var/www/html directory to a local directory the files copy accross but the rights change so that the main wp can no longer write to the directory.  This causes unwanted behaviour if you then try to install plugins (e.g. on attempting to install the wp importer it asks for ftp information).

**Comment by pierreozoux** [comment] 2015-08-26 08:25
The best answer is here:
http://stackoverflow.com/questions/23544282/what-is-the-best-way-to-manage-permissions-for-docker-shared-volumes

Look at all the answers, and you'll get the idea. If you don't want to modify the start script, I think the `data-only container` is the right approach for you.

If you have any doubts, please do not hesitate :) And don't forget, when the issue is solved for you, please close it.

I think it would be a good idea to add this to the documentation.

**Comment by Pym** [comment] 2015-10-02 14:35
@nigel-daniels have you found a solution? :\

**Comment by pierreozoux** [comment] 2015-10-02 17:08
I actually just map the `wp-content`.
I wanted to make a better documentation, didn't find time :/

Here you can base your work on that: https://github.com/indiehosters/wordpress/blob/master/docker-compose.yml (also gives you email :) )

**Comment by vyscond** [comment] 2016-06-23 00:19
@pierreozoux can you normally upload files, plugins with this setup? Even importing .xml to restore a wordpress?

**Comment by otravers** [comment] 2016-09-15 19:19
I'm mapping wp-content in my docker-compose file under Docker for Windows, but like nigel-daniels said I then have WP asking me for ftp credentials when I try to update/install plugins or themes.

`version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    links:
      - db
    volumes:
     - ./wp-content:/var/www/html/wp-content`

**Comment by vyscond** [comment] 2016-09-21 15:51
Guys. This seems to be an issue related to using VirtualBox to run the docker server. I've been using docker (beta) for like a month or two and this issues were gone.

**Comment by nicooga** [comment] 2017-10-10 17:32
@nigel-daniels Have you found a solution? I'm using a named volume via compose and having the same problem.

**Comment by nigel-daniels** [comment] 2017-10-10 18:40
@nicooga in the end I had to download the updates and apply them manually to the container.  I have not needed to use WP in Docker since Docker stopped using VirtualBox on MacOS so I cannot verify if the experience @vyscond has would be the same for me.  If you have the same problem then this may still be an issue.

**Comment by nicooga** [comment] 2017-10-18 03:32
@nigel-daniels I've "solved" by randomly trying changing permissions on /var/www/html. I don't know which of the commands I've run solved the issue, but the change only took effect after removing and restarting the container. Before that I've tweaked the entrypoint to install wordpress on a different directory.

**Comment by tianon** [comment] 2018-01-09 23:05
Closing since https://github.com/docker-library/wordpress/pull/249 allows for trivially modifying the user/group the image runs and/or `chown`s as (in some cases, by simply using `--user` on your `docker run` line).

**Closed by tianon** 2018-01-09 23:05 UTC
